# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       eventsview-extensions-github

# >> macros
# << macros
%define eve-version 0.1.9

Summary:    Eventsview plugin for GitHub notifications
Version:    0.1.2
Release:    0
Group:      Applications
License:    ASL 2.0
BuildArch:  noarch
URL:        https://github.com/nephros/%{name}
Source0:    %{name}-%{version}.tar.gz
Source100:  eventsview-extensions-github.yaml
Source101:  eventsview-extensions-github-rpmlintrc
Requires:   eventsview-extensions >= %{eve-version}
BuildRequires:  qt5-qttools-linguist
BuildRequires:  qt5-qmake
BuildRequires:  qml-rpm-macros

%description
${summary}.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_datadir}/lipstick/*/*
# >> files
# << files
